### ISSUE TITLE
Lines total is equal to Lines covered

### ISSUE THREAD

**Issue by OsirisTerje** [GeorgDangl/CoberturaConverter#2]
The code in the ConvertToCobertura() method sets LinesValid to same value as LInesCovered.  
LinesValid should be the total number.  

![bilde](https://user-images.githubusercontent.com/203432/40673018-cc031468-6370-11e8-83e5-0dcee072f084.png)

**Comment by GeorgDangl** [comment]
Thank you, I fixed it with a855318!

**Comment by GeorgDangl** [comment]
Fixed in [v1.1.3](https://github.com/GeorgDangl/CoberturaConverter/releases/tag/v1.1.3), should be available on NuGet in a few minutes.
