### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ...

### ISSUE THREAD

**Issue by sebalopez** [GeorgDangl/CoberturaConverter#3]
Hello,
I am running into this error when attempting to use the conversion from a Jenkins agent with .NET 4.7.1

```
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at CoberturaConverter.CommandLine.Program.<DotCoverToCobertura>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at CoberturaConverter.CommandLine.Program.DotCoverToCobertura(CoberturaConverterOptions options)
   at CoberturaConverter.CommandLine.Program.<Main>d__0.MoveNext()
```

This is the pipeline step:
`powershell '& C:\\CoberturaConverter.CommandLine.1.1.3\\tools\\net471\\CoberturaConverter.CommandLine.exe -i dotCover.xml -o cobertura.xml -s DotCover'`

Any ideas what could be missing?

thanks
Sebastian

**Comment by GeorgDangl** [comment]
Looks like something I'll have to look into, I don't know why it does that...
You do have .NET Framework 4.7.1 installed, do you?

The syntax is correct, this works on my machine:
```cli
PS C:\Users\Georg\Downloads\coberturaconverter.commandline.1.1.3\tools\net471> ./CoberturaConverter.CommandLine.exe -i c
overage.xml -o cobertura.xml -s DotCover
CoberturaConverter: Based on https://github.com/danielpalme/OpenCoverToCoberturaConverter
CoberturaConverter: Find out more at github.com/GeorgDangl/CoberturaConverter
Conversion finished
PS C:\Users\Georg\Downloads\coberturaconverter.commandline.1.1.3\tools\net471>
```

**Comment by sebalopez** [comment]
Apologies, I had it wrong, we have 4.6.2 . This on a Windows 10 Docker agent.

**Comment by GeorgDangl** [comment]
No Problem:)

**Comment by sebalopez** [comment]
sorry, do you mean 4.6.2 is not supported?

**Comment by GeorgDangl** [comment]
Ah, sorry, I thought you were updating.
I should be able to target 4.6.2, there's nothing blocking it. I will do it this this evening.

**Comment by sebalopez** [comment]
Thank you! this would be a life-saver for our TC to Jenkins migration project (dotCover does not integrate with Jenkins)

**Comment by GeorgDangl** [comment]
Could you try it with the latest beta on MyGet?  
https://www.myget.org/feed/dangl/package/nuget/CoberturaConverter.CommandLine

You should use `1.1.4-beta0011` or newer=)

**Comment by sebalopez** [comment]
Thank for you the quick turnaround, it seems to be working now :)

Only thing I wanted to clarify before closing, there is a lot less data in the Cobertura report. Basically just the line-rate at the package level. Is this the supposed behavior? 
I am attaching both files for reference.

Thanks again!

[reports.zip](https://github.com/GeorgDangl/CoberturaConverter/files/2116369/reports.zip)

**Comment by GeorgDangl** [comment]
Could you try with ReportType `DetailedXml` instead of `Xml`? I'm checking why the regular Xml doesnt produce output.

**Comment by GeorgDangl** [comment]
Classes without a file name are ignored when it's exported to Cobertura, see here:
https://github.com/GeorgDangl/CoberturaConverter/blob/develop/src/CoberturaConverter.Core/Cobertura/XmlExporter.cs#L96-L112

I think there was an error with the Jenkins Cobertura plugin, it failed when the Cobertura reports were missing the `filename` attribute, so I added that code. I'll update the README to include that info.

Thanks for spotting it!

**Comment by sebalopez** [comment]
trying now, but it doesn't seem DetailedXML is supported by the report command:

https://www.jetbrains.com/help/dotcover/dotCover__Console_Runner_Commands.html#report

**Comment by GeorgDangl** [comment]
I think that's an oversight in the documentation for dotCover, it should be working:

    C:\Users\JenkinsUser\.nuget\packages\jetbrains.dotcover.commandlinetools\2018.1.0-eap03\tools\dotCover.exe
    report
    /Source=C:\Jenkins\workspace\CoberturaConverter\output\coverage.snapshot
    /Output=C:\Jenkins\workspace\CoberturaConverter\output\coverage.xml
    /ReportType=DetailedXml

I'll verify with the latest dotCover version.

**Comment by GeorgDangl** [comment]
The `dotcover.exe help report` command lists it as an option:

```
PS C:\Users\Georg\.nuget\packages\jetbrains.dotcover.commandlinetools\2018.1.2\tools> ./dotCover.exe help report
JetBrains dotCover Console Runner 2018.1.2. Build 112.0.20180530.115319
Copyright (c) 2009-2018 JetBrains s.r.o. All rights reserved.
report: Creates a report by the specified snapshot.
usage: dotCover report [parameters]

Valid parameters:
  /Source=ARG             : (Required) Coverage snapshot file name
  /Output=ARG             : (Required) Resulting report file name
  /ReportType=ARG         : (Optional) [HTML|JSON|XML|DetailedXML|NDependXML]. A type of the report. XML by default
  /HideAutoProperties     : (Optional) Hides auto properties from report

Global parameters:
  /LogFile=ARG            : (Optional) Enables logging and allows specifying a log file name

It is possible to specify a part of the parameters or all of them in the configuration file.
usage: dotCover report <configuration file name> [parameters]

Configuration file format is described in the autogenerated sample.
usage: dotCover help report <configuration file name>
```

It's also working as expected. You can checkout this project and run `powershell ./build.ps1 Coverage` in the project root to verify.

**Comment by sebalopez** [comment]
You are right, it is supported. I was finally able to get the build to fail using the metrics :)
I am not yet seeing data in the Cobertura report, but seems to be an issue with the Jenkins plugin so I'll dig for it elsewhere.
Thanks a lot for your help!

**Comment by GeorgDangl** [comment]
Happy to help=)
